apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-extract-rdw-vehicles
  namespace: argo
  labels:
    app: python-rdw-vehicles
    environment: production
  annotations:
    description: "Weekly extraction of RDW vehicle data to S3"
spec:
  schedule: "0 0 * * 1"  # Runs every Monday at midnight
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

  workflowSpec:
    serviceAccountName: argo-workflows-server
    entrypoint: run-script
    onExit: notify-status
    activeDeadlineSeconds: 72000  # Must complete within 20 hour
    ttlStrategy:
      secondsAfterCompletion: 604800  # 7 days (7 * 24 * 60 * 60)
      successfulWorkflowTTL: "168h"   # 7 days in hours
      failedWorkflowTTL: "168h"       # 7 days in hours
    podGC:
      strategy: OnWorkflowCompletion
      labelSelector:
        matchLabels:
          workflows.argoproj.io/completed: "true"
      minSuccessfulWorkflowsToRetain: 1
      minFailedWorkflowsToRetain: 1

    templates:
    - name: run-script
      dag:
        tasks:
        - name: extract-rdw-data
          template: extract-rdw-data

    - name: extract-rdw-data
      initContainers:
      - name: git-clone
        image: alpine/git:latest
        command:
          - sh
          - -c
        args:
          - git clone https://github.com/walthertimmer/python-data-engineering.git /workspace
        volumeMounts:
          - name: scripts-volume
            mountPath: /workspace
      container:
        image: ghcr.io/walthertimmer/python-data-engineering/polars:latest
        command: ["python", "/workspace/PythonScripts/10_extract_rdw_vehicles.py"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "10Gi" 
            cpu: "6"
        env:
          - name: S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: python-data-engineering
                key: S3_ACCESS_KEY_ID
                namespace: argo
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: python-data-engineering
                key: S3_SECRET_ACCESS_KEY
                namespace: argo
          - name: S3_ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: python-data-engineering
                key: S3_ENDPOINT_URL
                namespace: argo
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: python-data-engineering
                key: S3_BUCKET
                namespace: argo
          - name: RDW_APP_TOKEN
            valueFrom:
              secretKeyRef:
                name: python-data-engineering
                key: RDW_APP_TOKEN
                namespace: argo
          - name: TARGET_LOCATION
            value: "raw/rdw-vehicles/"
        volumeMounts:
          - name: workdir
            mountPath: /workdir
          - name: scripts-volume
            mountPath: /workspace
        workingDir: /workdir
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
      volumes:
        - name: workdir
          emptyDir: {}
        - name: scripts-volume
          emptyDir: {}

    - name: notify-status
      steps:
      - - name: send-slack
          template: slack-notification
          arguments:
            parameters:
            - name: status
              value: "{{workflow.status}}"

    - name: slack-notification
      inputs:
        parameters:
        - name: status
      container:
        image: curlimages/curl
        command: ["/bin/sh", "-c"]
        args:
        - |
          MESSAGE=$(cat << EOF
          *Workflow Details*
          • Name: {{workflow.name}}
          • Status: {{inputs.parameters.status}}
          • Namespace: {{workflow.namespace}}
          • ID: {{workflow.uid}}
          • Start: {{workflow.creationTimestamp}}
          • Duration: {{workflow.duration}}
          • Node: {{pod.name}}
          EOF
          )
          echo "Sending Slack notification: $MESSAGE"
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"$MESSAGE\"}" \
          $(SLACK_WEBHOOK_URL) 2>&1
        env:
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: python-data-engineering
              key: SLACK_WEBHOOK_URL
