# .github/workflows/polars-docker-build.yml
name: Docker Build PolarsImage and Push

on:
  push:
    branches:
      - master
    paths: # only run on changes in the following directories
      - 'Docker/PolarsImage**'
      - '.github/workflows/polars-docker-build.yml'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # for multi-architecture builds
      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v3

      # for multi-architecture builds
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Polars image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Docker/PolarsImage.Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: false
          tags: |
            ghcr.io/${{ github.repository }}/polars:latest
            ghcr.io/${{ github.repository }}/polars:${{ github.sha }}

      - name: Create manifest lists for polars
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository }}/polars:latest \
          ghcr.io/${{ github.repository }}/polars:latest
      
      # Cleanups
      - name: Delete old polars image versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'python-data-engineering/polars'
          package-type: 'container'
          min-versions-to-keep: 3