# .github/workflows/docker-build.yml
name: Docker Build PythonImage and Push

on:
  push:
    branches:
      - master
    paths: # only run on changes in the following directories
      - 'Docker/**'
      - 'PythonScripts/**'
      - '.github/workflows/python-docker-build.yml'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # for multi-architecture builds
      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v3

      # for multi-architecture builds
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Docker/PythonImage.Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: false
          tags: |
            ghcr.io/${{ github.repository }}/python-scripts:latest
            ghcr.io/${{ github.repository }}/python-scripts:${{ github.sha }}

      - name: Create and push manifest list
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository }}/python-scripts:latest \
          ghcr.io/${{ github.repository }}/python-scripts:latest
      
      - name: Delete old package versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'python-data-engineering/python-scripts'
          package-type: 'container'
          min-versions-to-keep: 5