# .github/workflows/yofi-docker-build.yml
name: Docker Build Yofi Flask App and Push

on:
    push:
      branches:
        - master
      paths:
        - 'Yofi/**'
        - '.github/workflows/yofi-docker-build.yml'

permissions:
  contents: read
  packages: write

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
  
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
  
        - name: Build and push Yofi Flask image
          uses: docker/build-push-action@v5
          with:
            context: ./Yofi
            file: ./Yofi/Dockerfile
            push: true
            platforms: linux/amd64,linux/arm64
            provenance: false
            tags: |
              ghcr.io/${{ github.repository }}/yofi:latest
              ghcr.io/${{ github.repository }}/yofi:${{ github.sha }}
  
        - name: Create manifest lists for yofi
          run: |
            docker buildx imagetools create -t ghcr.io/${{ github.repository }}/yofi:latest \
            ghcr.io/${{ github.repository }}/yofi:latest
        
        # Cleanup old images
        - name: Delete old Yofi image versions
          uses: actions/delete-package-versions@v4
          with:
            package-name: 'python-data-engineering/yofi'
            package-type: 'container'
            min-versions-to-keep: 3